lib{backtrace}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBBACKTRACE_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBBACKTRACE_SHARED_BUILD

# Export options.
#
lib{backtrace}:
{
  cxx.export.poptions = "-I$out_root/libbacktrace/" "-I$src_root/libbacktrace/"
  cxx.export.libs = $intf_libs
}

liba{backtrace}: cxx.export.poptions += -DLIBBACKTRACE_STATIC
libs{backtrace}: cxx.export.poptions += -DLIBBACKTRACE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{backtrace}: bin.lib.version = "-$version.project_id"
else
  lib{backtrace}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libbacktrace/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
